version: "3"
services:
  php_8_instagramservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_8_instagramservice
    ports:
      - "8000:80"
    volumes:
      - ./config/sites/:/etc/apache2/sites-available/
      - ./config/sites-enabled:/etc/apache2/sites-enabled/
    restart: always
    